---
- name: "customize my arch"
  hosts: all
  become: true
  tasks:
    - name: dotfiles
      include_tasks: tasks/dotfiles.yml
      when: dotfiles

    - name: fonts
      include_tasks: tasks/fonts.yml
      when: fonts
