---
- name: Configure Arch
  hosts: localhost
  become: yes
  tasks:
    - name: Include Variables
      include_vars:
        file: vars/sysvars.yml

#################################################################################
# i3
#################################################################################
    - name: Check and install i3-wm package
      pacman:
        name: i3-wm
        state: present
      register: i3_status
      ignore_errors: yes

    - name: Check and install i3blocks package
      pacman:
        name: i3blocks
        state: present
      register: i3blocks_status
      ignore_errors: yes

    - name: Check and install i3lock package
      pacman:
        name: i3lock
        state: present
      register: i3lock_color_status
      ignore_errors: yes

      # Copy the default config
    - name: Copy i3 default config
      ansible.builtin.copy:
        src: "../files/i3/configHome"
        dest: "/home/{{ username }}/.config/i3/config"

    - name: Copy i3 Home config
      ansible.builtin.copy:
        src: "../files/i3/configHome"
        dest: "/home/{{ username }}/.config/i3/configHome"

    - name: Copy i3 Work config
      ansible.builtin.copy:
        src: "../files/i3/configWork"
        dest: "/home/{{ username }}/.config/i3/configWork"

    - name: Copy i3 config2
      ansible.builtin.copy:
        src: "../files/i3/config2"
        dest: "/home/{{ username }}/.config/i3/config2"

    - name: Copy home wallpaper
      ansible.builtin.copy:
        src: "../files/i3/home.jpg"
        dest: "/home/{{ username }}/.config/i3/wallpapers/home.jpg"

    - name: Copy work wallpaper
      ansible.builtin.copy:
        src: "../files/i3/work.jpg"
        dest: "/home/{{ username }}/.config/i3/wallpapers/work.jpg"

    - name: Copy i3blocks
      ansible.builtin.copy:
        src: "../files/i3/i3blocks"
        dest: "/home/{{ username }}/.config/i3blocks"

    - name: Install feh
      community.general.pacman:
        name: feh
        state: present

    - name: Install rofi
      community.general.pacman:
        name: rofi
        state: present

    - name: Install picom
      community.general.pacman:
        name: picom
        state: present

    - name: Install flameshot
      community.general.pacman:
        name: flameshot
        state: present

    - name: Install blueman
      community.general.pacman:
        name: blueman
        state: present

#################################################################################
# Add User to sudoers
#################################################################################
    - name: Create Yay User
      user:
        name: yay_user
        state: present
        groups: wheel
        append: yes
        createhome: yes
        shell: /bin/bash

    - name: Add yay_user to sudoers
      lineinfile:
        path: /etc/sudoers
        line: "yay_user ALL=(ALL) NOPASSWD: /usr/bin/yay"
        validate: 'visudo -cf %s'

#################################################################################
# Terminal/Shell
#################################################################################
    - name: Create alacritty config folder
      ansible.builtin.file:
        path: "/home/{{ username }}/.config/alacritty"
        state: directory
        mode: '0755'

    - name: Install Zsh and change user's shell
      community.general.pacman:
        name:
          - zsh
          - zsh-completions
          - zsh-syntax-highlighting
        state: present

    - name: Change "{{ username }}"'s shell to Zsh
      user:
        name: "{{ username }}"
        shell: /usr/bin/zsh

    - name: install firecode fonts
      ansible.builtin.shell:
        cmd: sudo -u {{ username }} yay -S --noconfirm ttf-firacode ttf-firacode-nerd

    - name: Install Neovim
      community.general.pacman:
        name: neovim
        state: present

#################################################################################
# Notes
#################################################################################
    - name: install Obsidian
      community.general.pacman:
        name: obsidian
        state: present

#################################################################################
# Thunderbird
#################################################################################
    - name: install Thunderbird
      community.general.pacman:
        name: thunderbird
        state: present

#################################################################################
# Remote Connection
#################################################################################
    - name: install Remmina (RDP)
      community.general.pacman:
        name: remmina
        state: present 

#################################################################################
# Applications
#################################################################################
    - name: install Chromium
      community.general.pacman:
        name:
        - chromium
        state: present

    - name: install Spotify
      ansible.builtin.shell:
        cmd: sudo -u yay_user /usr/bin/yay -S --noconfirm spotify

    - name: Install Discord
      ansible.builtin.shell:
        cmd: sudo -u yay_user /usr/bin/yay -S --noconfirm discord-electron

    - name: Install Minecraft
      ansible.builtin.shell:
        cmd: sudo -u yay_user /usr/bin/yay -S --noconfirm minecraft-launcher
      when: games

    - name: Install Steam
      ansible.builtin.shell:
        cmd: sudo -u yay_user /usr/bin/yay -S --noconfirm steam
      when: games

#################################################################################
# Yubikey
#################################################################################
    - name: install Yubikey
      ansible.builtin.shell:
        cmd: sudo -u yay_user /usr/bin/yay -S --noconfirm yubico-authenticator-bin yubikey-manager yubikey-personalization-gui

#################################################################################
# Monitor
#################################################################################
    - name: install Arandr and Autorandr
      community.general.pacman:
        name:
        - arandr
        - autorandr
        state: present

#################################################################################
# Storage
#################################################################################
    - name: install nextcloud-client
      community.general.pacman:
        name: nextcloud-client
        state: present

#################################################################################
# Virt-Manager
#################################################################################
    - name: Install KVM packages
      community.general.pacman:
        name:
        - qemu
        - virt-manager
        - virt-viewer
        - dnsmasq
        - vde2
        - bridge-utils
        - openbsd-netcat
        - dmidecode
        state: present
      when: vm

    - name: Install libguestfs
      community.general.pacman:
        name:
        - libguestfs
        state: present
      when: vm

    - name: enable libvirt service
      ansible.builtin.service:
        name: libvirtd.service
        state: started
        enabled: yes
      when: vm