---
- name: Configure Arch
  hosts: localhost
  become: yes
  tasks:
    - name: Include Variables
      include_vars:
        file: vars/sysvars.yml

#################################################################################
# Update system and mirrors and install yay
#################################################################################
    - name: Update system and mirrors
      community.general.pacman:
        update_cache: true
        upgrade: true
      when: update

    - name: Install yay
      community.general.pacman:
        name: yay
        state: present

#################################################################################
# i3
#################################################################################
    - name: Include i3 tasks
      ansible.builtin.include_tasks:
        file: tasks/i3.yaml
      when: i3

    - name: Install flameshot
      community.general.pacman:
        name: flameshot
        state: present

    - name: Install blueman
      community.general.pacman:
        name: blueman
        state: present

#################################################################################
# Terminal/Shell
#################################################################################
    - name: Include Alacritty tasks
      ansible.builtin.include_tasks:
        file: tasks/alacritty.yaml
      when: alacritty

    - name: Include zsh tasks
      ansible.builtin.include_tasks:
        file: tasks/ohmyzsh.yml
      when: zsh
      
    - name: Include fonts tasks
      ansible.builtin.include_tasks:
        file: tasks/fonts.yml
      when: fonts

    - name: Include Neovim tasks
      ansible.builtin.include_tasks:
        file: tasks/neovim.yaml
      when: neovim

    - name: Include vscode tasks
      ansible.builtin.include_tasks:
        file: tasks/vscode.yml
      when: vscode

#################################################################################
# Notes
#################################################################################
    - name: Include obsidian task
      ansible.builtin.include_tasks:
        file: tasks/obsidian.yml
      when: obsidian

#################################################################################
# Thunderbird
#################################################################################
    - name: install Thunderbird
      community.general.pacman:
        name: thunderbird
        state: present
      when: mail

#################################################################################
# Remote Connection
#################################################################################
    - name: install Remmina (RDP)
      community.general.pacman:
        name: remmina
        state: present
      when: remmina

#################################################################################
# Applications
#################################################################################
    
    - name: Include chromium task
      ansible.builtin.include_tasks:
        file: tasks/chromium.yml
      when: chromium

    - name: Include Spotify task
      ansible.builtin.include_tasks:
        file: tasks/spotify.yaml
      when: spotify

    - name: Include Discord task
      ansible.builtin.include_tasks:
        file: tasks/discord.yml
      when: discord

    - name: Include Minecraft task
      ansible.builtin.include_tasks:
        file: tasks/minecraft.yml
      when: minecraft

    - name: Include Steam task
      ansible.builtin.include_tasks:
        file: tasks/steam.yml
      when: steam

#################################################################################
# KeePaas
#################################################################################
    - name: Include KeePaas task
      ansible.builtin.include_tasks:
        file: tasks/keepaas.yml
      when: keepaas

#################################################################################
# Yubikey
#################################################################################
    - name: Include Yubkey task
      ansible.builtin.include_tasks:
        file: tasks/yubikey.yml
      when: yubikey

#################################################################################
# Monitor
#################################################################################
    - name: install Arandr and Autorandr
      community.general.pacman:
        name:
        - arandr
        - autorandr
        state: present

#################################################################################
# Storage
#################################################################################
    - name: install nextcloud-client
      community.general.pacman:
        name: nextcloud-client
        state: present

#################################################################################
# Virt-Manager
#################################################################################
    - name: Include Virt-Manager task
      ansible.builtin.include_tasks:
        file: tasks/VirtualManager.yml
      when: yubikey