---
- name: Configure Arch
  hosts: localhost
  become: yes

  tasks:
    - name: Include Variables
      include_vars:
        file: vars/sysvars.yml

#################################################################################
# i3
#################################################################################
    - name: Check and install i3-wm package
      pacman:
        name: i3-wm
        state: present
      register: i3_status
      ignore_errors: yes

    - name: Check and install i3blocks package
      pacman:
        name: i3blocks
        state: present
      register: i3blocks_status
      ignore_errors: yes

    - name: Check and install i3lock package
      pacman:
        name: i3lock
        state: present
      register: i3lock_color_status
      ignore_errors: yes

    - name: Copy i3 config
      ansible.builtin.copy:
        src: "../files/i3/config"
        dest: "/home/{{ username }}/.config/i3/config"

    - name: Copy i3 config1
      ansible.builtin.copy:
        src: "../files/i3/config1"
        dest: "/home/{{ username }}/.config/i3/config1"

    - name: Copy i3 config2
      ansible.builtin.copy:
        src: "../files/i3/config2"
        dest: "/home/{{ username }}/.config/i3/config2"

    - name: Copy wallpaper
      ansible.builtin.copy:
        src: "../files/i3/mountain.jpg"
        dest: "/home/{{ username }}/.config/i3/wallpapers/"

    - name: Copy i3blocks
      ansible.builtin.copy:
        src: "../files/i3/i3blocks"
        dest: "/home/{{ username }}/.config/i3blocks"

    - name: Install feh
      community.general.pacman:
        name: feh
        state: present

    - name: Install rofi
      community.general.pacman:
        name: rofi
        state: present

    - name: Install picom
      community.general.pacman:
        name: picom
        state: present

    - name: Install flameshot
      community.general.pacman:
        name: flameshot
        state: present

    - name: Install blueman
      community.general.pacman:
        name: blueman
        state: present
#################################################################################
# Terminal/Shell
#################################################################################
    - name: Create alacritty config folder
      ansible.builtin.file:
        path: "/home/{{ username }}/.config/alacritty"
        state: directory
        mode: '0755'

    - name: Install Zsh and change user's shell
      community.general.pacman:
        name:
          - zsh
          - zsh-completions
          - zsh-syntax-highlighting
        state: present

    - name: Change "{{ username }}"'s shell to Zsh
      user:
        name: "{{ username }}"
        shell: /usr/bin/zsh

    - name: install nerdfonts
      community.general.pacman:
        name:
        - ttf-firacode
        - ttf-firacode-nerd
        state: present

    - name: Install Neovim
      community.general.pacman:
        name: neovim
        state: present

#################################################################################
# Notes
#################################################################################
    - name: install Obsidian
      community.general.pacman:
        name:
        - obsidian
        state: present

#################################################################################
# Applications
#################################################################################
    - name: install Chromium
      community.general.pacman:
        name:
        - chromium
        state: present

    - name: install spotify
      community.general.pacman:
        name:
        - spotify
        state: present
    
    - name: install games
      community.general.pacman:
        name:
        - steam
        - minecraft-launcher
        - discord
        state: present
      when: games

#################################################################################
# Yubikey
#################################################################################
    - name: install Yubikey
      community.general.pacman:
        name:
          - yubico-authenticator-bin
          - yubikey-manager
          - yubikey-personalization-gui
        state: present

#################################################################################
# Monitor
#################################################################################
    - name: install Arandr and Autorandr
      community.general.pacman:
        name:
        - arandr
        - autorandr
        state: present