---
- name: install i3-wm packages
      community.general.pacman:
        name: 
        - i3-wm
        - xorg
        - i3status
        - dmenu
        - terminator
        state: present

    - name: Check and install i3blocks package
      community.general.pacman:
        name: i3blocks
        state: present

    - name: Check and install i3blocks package
      community.general.pacman:
        name: i3blocks
        state: absent

    - name: Check and install i3lock-color package
      community.general.pacman:
        name: i3lock-color
        state: present
        executable: yay
        extra_args: --builder /var/cache/yay
      become: no

    - name: Copy i3 default config
      ansible.builtin.copy:
        src: "../files/i3/configHome"
        dest: "/home/{{ username }}/.config/i3/config"

    - name: Copy i3 Home config
      ansible.builtin.copy:
        src: "../files/i3/configHome"
        dest: "/home/{{ username }}/.config/i3/configHome"

    - name: Copy i3 Work config
      ansible.builtin.copy:
        src: "../files/i3/configWork"
        dest: "/home/{{ username }}/.config/i3/configWork"

    - name: Copy i3 config2
      ansible.builtin.copy:
        src: "../files/i3/config2"
        dest: "/home/{{ username }}/.config/i3/config2"

    - name: Create wallpapers folder
      ansible.builtin.file:
        path: "/home/{{ username }}/.config/i3/wallpapers"
        state: directory

    - name: Copy home wallpaper
      ansible.builtin.copy:
        src: ""../files/wallpapers/home.jpg""
        dest: "/home/{{ username }}/.config/i3/wallpapers/home.jpg"

    - name: Copy work wallpaper
      ansible.builtin.copy:
        src: ""../files/wallpapers/work.jpg""
        dest: "/home/{{ username }}/.config/i3/wallpapers/work.jpg"

    - name: Copy i3blocks
      ansible.builtin.copy:
        src: "../files/i3/i3blocks"
        dest: "/home/{{ username }}/.config/i3blocks"

    - name: Copy i3lock script
      ansible.builtin.copy:
        src: "../files/i3/scripts/lock"
        dest: "/home/{{ username }}/.config/i3/scripts/"

    - name: Copy image for lightdm
      ansible.builtin.copy:
        src: "../files/wallpapers/work.jpg"
        dest: "/usr/pixmaps/lightdm_wallpaper.jpg"

    - name: Copy greeter for lightdm
      ansible.builtin.copy:
        src: "../files/i3/slick-greeter.conf"
        dest: "/etc/lightdm/"

    - name: Install feh
      community.general.pacman:
        name: feh
        state: present

    - name: Install rofi
      community.general.pacman:
        name: rofi
        state: present

    - name: Install picom
      community.general.pacman:
        name: picom
        state: present