- name: Detect Windows Partitions
  shell: "lsblk -o NAME,FSTYPE,START,END | grep 'ntfs' | awk '{print $1,$3,$4}'"
  register: windows_partitions
  ignore_errors: yes

- name: Create Swap Partition
  parted:
    device: /dev/sda
    number: 1
    state: present
    part_start: "{{ windows_partitions.stdout_lines[0].split(' ')[1] | default('1MiB') }}"
    part_end: "{{ windows_partitions.stdout_lines[0].split(' ')[2] | default('2GiB') }}"
  when: windows_partitions.stdout_lines | length > 0

- name: Create Root Partition
  parted:
    device: /dev/sda
    number: 2
    state: present
    part_start: "{{ windows_partitions.stdout_lines[1].split(' ')[1] | default('2GiB') }}"
    part_end: "{{ windows_partitions.stdout_lines[1].split(' ')[2] | default('100%') }}"
  when: windows_partitions.stdout_lines | length > 1

- name: Format Swap Partition
  filesystem:
    fstype: swap
    dev: /dev/sda1
  when: windows_partitions.stdout_lines | length > 0

- name: Format Root Partition
  filesystem:
    fstype: ext4
    dev: /dev/sda2
  when: windows_partitions.stdout_lines | length > 1

- name: Mount Partitions
  mount:
    path: "{{ item.mount_point }}"
    src: "{{ item.device }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    opts: "{{ item.mount_options }}"
  loop:
    - { mount_point: /mnt, device: /dev/sda2, fstype: ext4, mount_options: defaults }
    - { mount_point: /mnt/boot, device: /dev/sda2, fstype: ext4, mount_options: defaults }
  when: "item.device != '/dev/sda1'"

- name: Install Arch Linux Base System
  command: pacstrap /mnt base base-devel linux linux-firmware networkmanager

- name: Set Hostname
  hostname:
    name: myArch
    update_hostname: yes

- name: Set Timezone Zurich
  command: timedatectl set-timezone Europe/Zurich

- name: Configure Locale for Switzerland
  lineinfile:
    path: /etc/locale.gen
    line: "de_CH.UTF-8 UTF-8"
  notify: Generate Locale

- name: Generate Locale
      command: locale-gen

- name: Set Locale to Swiss German
  lineinfile:
    path: /etc/locale.conf
    line: "LANG=de_CH.UTF-8"

- name: Set Keymap to Swiss German
  lineinfile:
    path: /etc/vconsole.conf
    line: "KEYMAP=de_CH-latin1"

- name: Install GRUB
  command: pacman -S grub
  notify: Install GRUB

- name: Install GRUB
  command: >
    grub-install --target=x86_64-efi /dev/sda
    grub-mkconfig -o /boot/grub/grub.cfg

- name: Update Package Database
  pacman: 
    update_cache: yes

- name: Generate and Write Fstab File
  command: genfstab -U /mnt >> /mnt/etc/fstab