- name: install yubikey
  community.general.pacman:
    name:
    - yubico-authenticator-bin
    - yubikey-manager
    - yubikey-personalization-gui
    state: present
    executable: yay
    extra_args: --builder /var/cache/yay
  become: no