Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |lb|
    lb.memory = 2048
    lb.cpus = 20
  end

  config.vm.define "arch" do |arch|
    arch.vm.box = "generic/arch"
    arch.vm.hostname = "arch"
  end

  config.vm.define "controller" do |ctrl|
    ctrl.vm.box = "generic/ubuntu2204"
    ctrl.vm.hostname = "controller"
    #ctrl.vm.provision = "shell", path: "scripts/ansible-install.sh"
    #ctrl.vm.provision = "file", souce: "../playbook.yml", destination: "~/.playbook.yml"
  end

end
